### ISSUE TITLE
Permissions incorrectly set for dir /RND/hadoop-2.8.0/tmp-nm/filecache, should be rwxr-xr-x, actual value = rw-rw-rw-

### ISSUE THREAD

**Issue by CPattanayak** [MuhammadBilalYar/Hadoop-On-Window#23]
after running start-all.cmd in window 10 getting 
rg.apache.hadoop.yarn.exceptions.YarnRuntimeException: Failed to setup local dir /RND/hadoop-2.8.0/tmp-nm, which was marked as good.
        at org.apache.hadoop.yarn.server.nodemanager.containermanager.localizer.ResourceLocalizationService.checkAndInitializeLocalDirs(ResourceLocalizationService.java:1533)
        at org.apache.hadoop.yarn.server.nodemanager.containermanager.localizer.ResourceLocalizationService$1.onDirsChanged(ResourceLocalizationService.java:271)
        at org.apache.hadoop.yarn.server.nodemanager.DirectoryCollection.registerDirsChangeListener(DirectoryCollection.java:197)
        at org.apache.hadoop.yarn.server.nodemanager.LocalDirsHandlerService.registerLocalDirsChangeListener(LocalDirsHandlerService.java:242)
        at org.apache.hadoop.yarn.server.nodemanager.containermanager.localizer.ResourceLocalizationService.serviceStart(ResourceLocalizationService.java:371)
        at org.apache.hadoop.service.AbstractService.start(AbstractService.java:193)
        at org.apache.hadoop.service.CompositeService.serviceStart(CompositeService.java:120)
        at org.apache.hadoop.yarn.server.nodemanager.containermanager.ContainerManagerImpl.serviceStart(ContainerManagerImpl.java:490)
        at org.apache.hadoop.service.AbstractService.start(AbstractService.java:193)
        at org.apache.hadoop.service.CompositeService.serviceStart(CompositeService.java:120)
        at org.apache.hadoop.yarn.server.nodemanager.NodeManager.serviceStart(NodeManager.java:369)
        at org.apache.hadoop.service.AbstractService.start(AbstractService.java:193)
        at org.apache.hadoop.yarn.server.nodemanager.NodeManager.initAndStartNodeManager(NodeManager.java:637)
        at org.apache.hadoop.yarn.server.nodemanager.NodeManager.main(NodeManager.java:684)
Caused by: org.apache.hadoop.yarn.exceptions.YarnRuntimeException: Permissions incorrectly set for dir /RND/hadoop-2.8.0/tmp-nm/filecache, should be rwxr-xr-x, actual value = rw-rw-rw-
        at org.apache.hadoop.yarn.server.nodemanager.containermanager.localizer.ResourceLocalizationService.checkLocalDir(ResourceLocalizationService.java:1560)
        at org.apache.hadoop.yarn.server.nodemanager.containermanager.localizer.ResourceLocalizationService.checkAndInitializeLocalDirs(ResourceLocalizationService.java:1528)
        ... 13 more
19/10/02 18:38:18 INFO ipc.Server: Stopping IPC Server Responder
19/10/02 18:38:18 WARN nodemanager.NodeResourceMonitorImpl: org.apache.hadoop.yarn.server.nodemanager.NodeResourceMonitorImpl is interrupted. Exiting.

node manager startup eventhough it is having correct permission

**Comment by MuhammadBilalYar** [comment]
run **Hadoop namenode -format** and then delete '**tmp**' folder from C drive, after that make sure the Hadoop folder is not marked as Read Only.

**Comment by CPattanayak** [comment]
It worked for me thanks

**Comment by alpeshnikumbh812** [comment]
> Hadoop

can you tell me in which directory i have to set permition

**Comment by vignesan-siva** [comment]
i'm facing above issue anyone help i delete tem folder but not work again shown this error

**Comment by alpeshnikumbh812** [comment]
Try to run with admin console

**Comment by vignesan-siva** [comment]
The admin console works perfectly in my office don't use the admin console use some other different ways run hadoop there is any possibility available or Hadoop only run admin console only

**Comment by xianyuli** [comment]
I have encountered the same issue. The reason for my error was that my computer was logged in using a Microsoft account. After switching to a local administrator account, logging out, and then restarting the command prompt, the problem no longer occurred.
